name: Generate references

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - uses: docker://pandoc/core:2.9
        with:
          args: >- # allows you to break string into multiple lines
            -s
            --output=README.md
            --bibliography source/references.bib 
            --citeproc 
            --csl source/apa.csl
            -t gfm
            source/source.md