# name: Generate references

# on: push

# jobs:
#   convert_via_pandoc:
#     runs-on: ubuntu-18.04
#     steps:
#       - uses: docker://pandoc/core:2.9
#         with:
#           args: >- # allows you to break string into multiple lines
#             -s
#             --output=README.md
#             --bibliography source/references.bib 
#             --citeproc 
#             --csl source/apa.csl
#             -t gfm
#             source/source.md

name: Process README markdown

on: [push]

jobs:
  convert_via_pandoc:
    name: Convert via Pandoc
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      # - run: mkdir output
      - uses: maxheld83/pandoc@v2
        with:
          args: "--output=README.md -t gfm --bibliography source/references.bib --csl source/apa.csl source/source.md"
          # args: "--help"
      - name: Commit files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "Add changes" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          branch: ${{ github.ref }}
