# name: Generate references

# on: push

# jobs:
#   convert_via_pandoc:
#     runs-on: ubuntu-18.04
#     steps:
#       - uses: docker://pandoc/core:2.9
#         with:
#           args: >- # allows you to break string into multiple lines
#             -s
#             --output=README.md
#             --bibliography source/references.bib 
#             --citeproc 
#             --csl source/apa.csl
#             -t gfm
#             source/source.md

name: Process README markdown

on: [push]

jobs:
  convert_via_pandoc:
    name: Convert via Pandoc
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - run: mkdir output
      - uses: maxheld83/pandoc@v2
        with:
          args: "--output=output/README.md -t gfm --bibliography source/references.bib --citeproc --csl source/apa.csl source/source.md"
      - uses: actions/upload-artifact@master
        with:
          name: output
          path: output