# name: Generate references

name: Generate README with references and pdf version of markdown source

on: [push]

jobs:
  convert_via_pandoc:
    name: Converting via Pandoc
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3

      - name: Generate new README.md
        uses: maxheld83/pandoc@v2
        with:
          args: "--output=README.md -t gfm --toc --bibliography source/references.bib --csl source/apa.csl source/source.md"

      - name: Generate new pdf version
        uses: maxheld83/pandoc@v2
        with:
          args: "--output=output/oceania-data-guide.pdf --bibliography source/references.bib --csl source/apa.csl source/source.md"

      - name: Commit files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "Add changes" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          branch: ${{ github.ref }}
